---
title: Deployment Options
---

== Python Deployment Options
toc::[]

The `python` source-to-image (S2I) builders provide a number of different ways of deploying a Python application. You can use the bundled support for hosting a WSGI application via Gunicorn, or you can choose to use other WSGI servers such as mod_wsgi-express and uWSGI. Prefer to run asynchronous event based applications, you can use frameworks such as Tornado, Twisted, or newer asyncio based systems.

=== Automatic Detection

The basis for determining which deployment mechanism is used is based on the following detection algorithm:

1. If a Python code file named `app.py` exists in the top level directory of the source code repository, it will be executed as a Python script. You can run from `app.py` any Python web server or application framework, so long as it accepts inbound HTTP connections on port 8080. If a Python web server does not provide a way of being started up by importing a Python module and invoking it via an API call, you can use `exec` functions from the `os` module to execute a separate command line program.

2. If the `gunicorn` package has been installed via the `requirements.txt` or `setup.py` files, and a `wsgi.py` file is located in the top level directory of the source code repository, or a sub directory down to at most two levels, the Gunicorn WSGI server will be used to host the WSGI application. When located in a sub directory, the `wsgi.py` file must be part of a Python package and will be imported by its module path, rather than by file system path. The name of the WSGI application entry point callable contained in the `wsgi.py` file must be called `application`.

3. If the `gunicorn` package has been installed via the `requirements.txt` or `setup.py` files, but a `wsgi.py` file could not be found, and a `setup.py` file had been used, the name of the package installed by the `setup.py` will be taken to contain the WSGI application entry point callable.

4. If the `Django` package has been installed via the `requirements.txt` or `setup.py` files, and a `manage.py` file is located in the top level directory of the source code repository, or an immediate sub directory, it will be assumed that a Django based application is being used. For this case the Django application will be started using the Django development server. As the Django development server is not suitable for production use, this method should only be relied on for initial setup or testing.

For (1), the name of the `app.py` file can be overridden by setting the `APP_FILE` environment variable.

For (2) and (3), the search for a module containing the WSGI application entry point callable will be skipped if the module path is set using the `APP_MODULE` environment variable. If specifying the module containing the WSGI application entry point callable in this way, you must still have installed the `gunicorn` package via the `requirements.txt` or `setup.py` files.

=== Application Logging

OpenShift expects that all logging from your application, or a web server, is directed to the console (standard output/error stream). If the web server or application framework logs to files, the log output will not be available through OpenShift. 

When the bundled support for hosting a WSGI application via Gunicorn is used, the source-to-image builder scripts will ensure that Gunicorn is started with the appropriate options to direct any log output to the console so that it can be captured by OpenShift.

If you are using a different WSGI server or application framework with its own bundled web server, you will need to ensure that it sends output to the console. You should also configure the Python logging module or any framework specific logging mechanism to use the console.

Any logging generated and output to the console can be viewed using the `oc logs` command or via the OpenShift web console.

=== Inbound HTTP Connections

If you are not using the bundled support for hosting a WSGI application using Gunicorn, and are using an alternate WSGI server, or a custom Python web server, the server must accept inbound HTTP connections on port 8080. If the server would by default only accept HTTP connections on a local network interface, such as `localhost` or `127.0.0.1`, you must tell it to bind to the network address `0.0.0.0` so that it can accept HTTP connections on any network interface.

When connections are received from another application running in the same OpenShift project, they will be a direct connection from that other application. When an application is exposed to the Internet, inbound connections will arrive via a HTTP proxy. In this case the Python web server or application must handle proxy headers which provide details of the remote client.

* `X-Forwarded-For` - Specifies the remote client address and any proxies which the request has passed through.
* `X-Forwarded-Port` - The exposed port on which the inbound HTTP connection was accepted.
* `X-Forwarded-Proto` - The protocol scheme identifying the type of connection made: `http` or `https`.

The `python` source-to-image builders do not directly support termination of TLS connections for HTTPS. If your application requires that a remote client use a secure connection, you should enable use of a secure connection when exposing the servive, specifying `edge` termination, and optionally supplying your SSL certificate details.

=== Hosting of Static Files

The `python` source-to-image builders do not provide any bundled functionality for hosting static files. If you are using the Gunicorn WSGI server, you will need to use a WSGI middleware package such as link:https://pypi.python.org/pypi/whitenoise[WhiteNoise] to host static files, or host them using a separately deployed web server. If using a separate a web server, you can still have the static files available under the same exposed host name, by using a path based route when exposing the separate web server.

The alternative to using a separate web server, is to use a WSGI server such as mod_wsgi-express or uWSGI, which provide direct support for hosting static files.

=== Running With Gunicorn

Gunicorn is the default deployment option for a WSGI application. To use the bundled support for running Gunicorn, the requirements are as follows:

* The `gunicorn` package must be installed via the `requirements.txt` or `setup.py` files.
* A `wsgi.py` file must be located in the top level directory of the source code repository, or a sub directory down to at most two levels.
* The `wsgi.py` file must be part of a Python package, if in a sub directory, and will be imported by its module path, rather than by file system path.
* The name of the WSGI application entry point callable contained in the `wsgi.py` file must be called `application`.

The `APP_CONFIG` environment variable can be set to the name of a Python code file including any additional Gunicorn configuration settings. This will be supplied to Gunicorn using the `--config` option of `gunicorn`. The configuration file might be used to override the name of the WSGI application entry point callable, or set the number of Gunicorn worker processes.

The configuration file can also be used to set the type of worker, allowing you to use alternate workers such as those for `gevent` or `eventlet`. If using an alternate type of worker, you will need to ensure that any additional Python packages required for it are listed in the `requirements.txt` or `setup.py` file.

=== Running With Apache/mod_wsgi

=== Running With uWSGI

=== Running With Waitress

'''