---
title: Environment Variables
---

== Python Environment Variables
toc::[]

The `python` source-to-image (S2I) builders support the following environment variables:

[cols="1,2,3",options="header"]
|===
|Variable Name |Configuration |Purpose

|APP_FILE
|Deployment
|This environment variable specifies the name of a Python script file, which if it exists, will be executed to run the Python web application. By default the name of the script file is `app.py`.

|APP_MODULE
|Deployment
|This environment variable can be set to specify the name of a Python module containing the WSGI application entry point. By default the name of the Python module is determined by searching for a `wsgi.py` file and translating its location into a Python module name.

|DISABLE_COLLECTSTATIC
|Build
|This environment variable controls whether the command `python manage.py collectstatic` is run during the building of the application image. This command would normally be run when a `manage.py` script exists and it was believed a Django application was being deployed. This would be required to be set (to a non empty value) if deploying a Flask application and the Flask-Script add-on was used to provide a `manage.py` for the Flask application. 

|DISABLE_MIGRATE
|Deployment
|This environment variable controls whether the command `python manage.py migrate` is run prior to the web application being started. This command would normally be run when a `manage.py` script exists and it was believed a Django application was being deployed. This would be required to be set (to a non empty value) if deploying a Flask application and the Flask-Script add-on was used to provide a `manage.py` for the Flask application.

Note that automatic execution of database migration when deploying a Django application is provided as a convenience when initially getting a Django application running. It is recommended that database migration as part of the start up process of the Django application be disabled for production deployments. Execution of database migration should instead be triggered using life cycle hooks defined as part of the deployment configuration.

|===

Environment variables can be set when initially creating a web application from the OpenShift web console, by selecting _Show advanced routing, build, and deployment options_. If using the `oc` command line, environment variables can be set using the `--env` option.

[source]
--
$ oc new-app python~https://gitlab.com/osevg/python-django-modwsgi.git --env DISABLE_MIGRATE=1
--

In the case of a web application which is already running, environment variables can be set from the build or deployment configuration through the OpenShift web console, or `oc set env` can be used from the command line.

'''